# Generated by Django 6.0.1 on 2026-02-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='debt',
            name='note',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_source',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ewallet_balance',
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('monthly_summary', 'Monthly Summary'), ('category_breakdown', 'Category Breakdown'), ('goal_progress', 'Goal Progress')], max_length=20),
        ),
    ]
