# Generated by Django 5.2.4 on 2026-02-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='balance',
        ),
    ]
