# Generated by Django 6.0.1 on 2026-02-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack_app', '0002_alter_budget_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.RemoveField(
            model_name='budget',
            name='category',
        ),
        migrations.AddField(
            model_name='budget',
            name='year',
            field=models.PositiveSmallIntegerField(default=2026),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
