# Generated by Django 5.2.4 on 2026-02-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack_app', '0002_remove_userprofile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
