# Generated by Django 6.0.1 on 2026-02-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack_app', '0003_alter_budget_options_remove_budget_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-month']},
        ),
        migrations.RemoveField(
            model_name='budget',
            name='year',
        ),
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.DateField(),
        ),
    ]
