# Generated by Django 6.0.1 on 2026-02-12 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack_app', '0004_alter_budget_options_remove_budget_year_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='debt',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='goal',
            unique_together=set(),
        ),
    ]
